name: bunkalist
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
   # Service locator
  get_it: 3.0.3
  # Bloc for state management
  flutter_bloc: 2.0.0
  # Value equality
  equatable: 0.5.1
  # Functional programming thingies
  dartz: 0.8.9
  # Remote API
  connectivity: 0.4.6+1
  http: 0.12.0+4 
  # Local cache
  shared_preferences: 0.5.6
  # Swap the connectivity package for this
  data_connection_checker: 0.3.4
  # Video player for Youtube videos
  youtube_player_flutter: ^6.0.3+2
  # URL laucher
  url_launcher: ^5.1.2
  # bottom navigation
  fancy_bottom_navigation: ^0.3.2
  # firebase auth
  firebase_auth: ^0.15.4
  # flutter secure storage
  flutter_secure_storage: ^3.3.1+1
  # google sign in
  google_sign_in: ^4.1.4
  # google fonts
  google_fonts: ^0.3.9
  # firebase core
  firebase_core: ^0.4.4+2
  # cloud firestore
  cloud_firestore: ^0.13.4    
  # flushbar 
  flushbar: ^1.10.0
  # fluid slider
  flutter_fluid_slider: ^1.0.2
  # format date &  provides internationalization
  intl: ^0.16.0
  # carrusel slider
  carousel_slider: ^1.4.1
  # snap floating container
  snap: ^1.0.5
  # App Review
  app_review: ^1.1.0+1
  # Image Picker
  image_picker: ^0.6.4
  # firebase storage
  firebase_storage: ^3.1.5
  # unique id generator
  uuid: ^2.0.4
  # svg render
  flutter_svg: ^0.17.4
  # flutter in app purchase
  flutter_inapp_purchase: ^2.2.0
  # admob native flutter
  flutter_native_admob: ^2.1.0
  # in app update
  in_app_update: ^1.1.7
  # circular chart 
  flutter_circular_chart: ^0.1.0
  # chart common
  charts_flutter: ^0.9.0
  # infinite list view
  infinite_listview: ^1.0.1+1
  # facebook ads
  facebook_audience_network: ^0.6.1
  # tab indicator rounded
  md2_tab_indicator: ^1.0.2
  # purchases
  purchases_flutter: ^1.0.4
  # flutter neumorphic
  flutter_neumorphic: ^3.0.1

  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.3
  flutter_platform_widgets: 0.30.1
  flutter_swiper: 1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:   
  flutter_launcher_icons:
  mockito: 

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/launcher-icon.png"
  adaptive_icon_background: "#662299"
  adaptive_icon_foreground: "assets/icon/launcher-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - lang/en.json
   - lang/de.json
   - lang/es.json
   - lang/fr.json
   - lang/hi.json
   - lang/it.json
   - lang/ja.json
   - lang/ko.json
   - lang/pt.json
   - lang/ru.json
   - assets/
   
  #  - lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
          style: normal
        - asset: fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: fonts/SourceSansPro-ExtraLight.ttf
          weight: 100
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 200
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 300
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 400
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 500
        - asset: fonts/SourceSansPro-Black.ttf
          weight: 600
        - asset: fonts/SourceSansPro-ExtraLightItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/SourceSansPro-LightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/SourceSansPro-Italic.ttf
          style: italic
          weight: 300
        - asset: fonts/SourceSansPro-SemiBoldItalic.ttf
          style: italic
          weight: 400
        - asset: fonts/SourceSansPro-BoldItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/SourceSansPro-BlackItalic.ttf
          style: italic
          weight: 600              

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
