name: bunkalist
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

analyzer:
  enable-experiment:
    - non-nullable

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  admob_flutter: ^1.0.1
  app_review: ^1.1.0+1
  carousel_slider: ^3.0.0
  charts_flutter: ^0.10.0
  cloud_firestore: ^0.13.4
  connectivity: 0.4.6+1
  convex_bottom_bar: ^2.6.0
  cupertino_icons: 0.1.3
  dartz: 0.8.9
  data_connection_checker: 0.3.4
  device_info: ^1.0.0
  dotted_border: ^1.0.7
  enum_to_string: ^1.0.13
  equatable: 0.5.1
  facebook_audience_network: ^0.6.1
  fancy_bottom_navigation: ^0.3.2
  firebase_auth: ^0.15.4
  firebase_core: ^0.4.4+2
  firebase_messaging: ^6.0.16
  firebase_storage: ^3.1.5
  flushbar: ^1.10.0
  flutter:
    sdk: flutter
  flutter_bloc: 4.0.0
  flutter_countdown_timer: ^2.1.0
  flutter_fluid_slider: ^1.0.2
  flutter_inapp_purchase: ^2.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_admob: ^2.1.0
  flutter_neumorphic: ^3.0.1
  flutter_secure_storage: ^3.3.1+1
  flutter_stack_card: ^0.2.0+1
  flutter_svg: ^0.19.3
  flutter_swiper: 1.1.6
  get_it: 3.0.3
  google_fonts: ^0.3.9
  google_sign_in: ^4.1.4
  grouped_list: null
  http: 0.12.0+4
  in_app_review: ^1.0.4
  in_app_update: ^1.1.7
  infinite_listview: ^1.0.1+1
  intl: ^0.17.0
  intro_slider: ^2.3.1
  md2_tab_indicator: ^1.0.2
  package_info: ^0.4.3+4
  percent_indicator: ^2.1.9+1
  provider: ^4.0.5
  purchases_flutter: ^2.0.3
  reorderables: null
  rxdart: ^0.26.0
  shared_preferences: 0.5.6
  snap: ^1.0.5
  tab_indicator_styler: ^1.0.0
  timeago: ^3.2.2
  url_launcher: ^5.1.2
  uuid: ^2.0.4
  vertical_card_pager: ^1.4.0
  youtube_player_flutter: ^7.0.0+7

dev_dependencies:
  build_runner: null
  flutter_launcher_icons: null
  flutter_test:
    sdk: flutter
  json_serializable: null
  mockito: null

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/launcher-icon.png"
#   adaptive_icon_background: "#662299"
#   adaptive_icon_foreground: "assets/icon/launcher-icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/en.json
    - lang/de.json
    - lang/es.json
    - lang/fr.json
    - lang/hi.json
    - lang/it.json
    - lang/ja.json
    - lang/ko.json
    - lang/pt.json
    - lang/ru.json
    - lang/id.json
    - assets/

  #  - lang/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
          style: normal
        - asset: fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: fonts/SourceSansPro-ExtraLight.ttf
          weight: 100
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 200
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 300
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 400
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 500
        - asset: fonts/SourceSansPro-Black.ttf
          weight: 600
        - asset: fonts/SourceSansPro-ExtraLightItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/SourceSansPro-LightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/SourceSansPro-Italic.ttf
          style: italic
          weight: 300
        - asset: fonts/SourceSansPro-SemiBoldItalic.ttf
          style: italic
          weight: 400
        - asset: fonts/SourceSansPro-BoldItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/SourceSansPro-BlackItalic.ttf
          style: italic
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
